name: Deploy Lambdas

on:
  push:
    branches:
      - main
    paths:
      - 'backend/lambda/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd backend/lambda
          npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Zip and deploy Lambda functions
        run: |
          cd backend/lambda
          for func in getBooks getBook createBook updateBook deleteBook; do
            echo "Deploying $func..."
            zip -r "${func}.zip" "${func}.js" node_modules package.json
            aws lambda update-function-code \
              --function-name "HomeLibrary$(tr '[:lower:]' '[:upper:]' <<< ${func:0:1})${func:1}" \
              --zip-file "fileb://${func}.zip" \
              --region $AWS_REGION
            echo "✅ $func deployed successfully"
          done 